spring:
  application:
    name: ScanwordApp
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  session:
    timeout: -1
  flyway:
    baseline-on-migrate: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  web:
    resources:
      add-mappings: true
