spring:
  application:
    name: ScanwordApp
  datasource:
    url: jdbc:postgresql://192.168.1.66:5432/ScanwordApp
    username: ydek
    password: remote
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true